# BlueALSA - dependabot.yaml
# SPDX-FileCopyrightText: 2023-2025 BlueALSA developers
# SPDX-License-Identifier: MIT

version: 2
updates:

  # Check for updates to GitHub Actions every week
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
