sudo: true
dist: xenial

language: c

addons:
  apt:
    packages:
      - check
      - libasound2-dev
      - libbluetooth-dev
      - libbsd-dev
      - libfdk-aac-dev
      - libglib2.0-dev
      - libncurses5-dev
      - libreadline-dev
      - libsbc-dev

before_script:
  - mkdir -p m4
  - sed -i -e 's$/var/run$.$' configure.ac
  - autoreconf --install && mkdir build && cd build

script:
  - ../configure --enable-test && make && make check
  - cat test/*.log
  - ../configure --enable-test --enable-debug && make && make check
  - cat test/*.log
  - ../configure --enable-test --enable-aac --enable-msbc && make && make check
  - cat test/*.log
